In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
Xtrain = pickle.load(open('Xtrain_ANN.data', 'rb'))
Ytrain = pickle.load(open('Ytrain_ANN.data', 'rb'))

In [3]:
from sklearn.decomposition import PCA

In [4]:
pca = PCA(n_components=100)

In [5]:
pca.fit(Xtrain)

PCA(copy=True, iterated_power='auto', n_components=100, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [6]:
pca.explained_variance_

array([1.53691052, 0.51650046, 0.49245962, 0.44320213, 0.3996141 ,
       0.3728763 , 0.34904255, 0.30409751, 0.28935477, 0.22907146,
       0.20430351, 0.16881411, 0.1497853 , 0.13200864, 0.12425354,
       0.10653815, 0.10525059, 0.09735936, 0.09501407, 0.08820326,
       0.08559168, 0.08331366, 0.07050821, 0.06771544, 0.06389252,
       0.0575539 , 0.0527528 , 0.04716308, 0.04583233, 0.0448552 ,
       0.04237726, 0.04029173, 0.03876344, 0.03744882, 0.03641377,
       0.03532321, 0.03020686, 0.02742895, 0.02592265, 0.0257678 ,
       0.02362075, 0.02228836, 0.02159805, 0.02010956, 0.01944478,
       0.0177831 , 0.01717802, 0.01652731, 0.01607151, 0.01524204,
       0.01433245, 0.01363158, 0.01287726, 0.01244912, 0.01234272,
       0.01218818, 0.01184055, 0.01143178, 0.01127677, 0.01069909,
       0.01055573, 0.00980349, 0.00898263, 0.00890887, 0.0083982 ,
       0.00790664, 0.00773449, 0.00750846, 0.00715642, 0.00698992,
       0.00681661, 0.00666485, 0.00647876, 0.00585622, 0.00558

In [7]:
pca.singular_values_

array([952.68336905, 552.28042499, 539.27415161, 511.59373042,
       485.78566609, 469.25259601, 454.00797364, 423.77050403,
       413.37062837, 367.79835612, 347.34592657, 315.7393151 ,
       297.41227537, 279.20646124, 270.88107937, 250.8284875 ,
       249.30819895, 239.78010334, 236.87447345, 228.22678272,
       224.82265666, 221.81064765, 204.05353693, 199.97152569,
       194.24475783, 184.35786944, 176.50094352, 166.88810337,
       164.5168106 , 162.75364122, 158.19425543, 154.25250857,
       151.29878161, 148.71109277, 146.64158296, 144.42899561,
       133.56020352, 127.27083415, 123.7268522 , 123.35675119,
       118.10577656, 114.72639376, 112.93579206, 108.97468439,
       107.15829958, 102.47739453, 100.71885669,  98.7928138 ,
        97.42100034,  94.87371602,  91.99929017,  89.72166876,
        87.20390846,  85.74199281,  85.37479225,  84.83864578,
        83.62000865,  82.1639458 ,  81.60498775,  79.48728201,
        78.95298006,  76.08774487,  72.83265918,  72.53

In [8]:
Xtrain = pd.DataFrame(data=pca.transform(Xtrain))
Xtrain.head()

0         1         2         3         4         5         6   \
0  0.147497 -0.128136 -0.555639  0.292194 -0.168896  1.501089  0.938601   
1  0.215837 -0.316249 -0.480825  1.065285 -0.388672  0.314880  0.001645   
2 -1.357071  0.254334  0.212074 -0.170978  0.917643 -0.101091  0.896096   
3 -0.699646  0.090907 -0.430041  0.786889 -0.922474 -0.422978 -0.176333   
4  2.361831  0.017103  1.310205  1.881893 -0.120688 -0.377364  0.510768   

         7         8         9   ...        90        91        92        93  \
0  0.363685 -0.396042 -0.006756  ... -0.008526  0.016535 -0.040768 -0.067105   
1 -0.663226 -1.176959  0.081671  ... -0.003357 -0.009909  0.010030  0.010203   
2  0.363993  0.523769 -0.618342  ...  0.006307 -0.049741  0.017028 -0.000441   
3  0.432002  0.212042 -0.075838  ...  0.004868 -0.027412 -0.053747 -0.016984   
4 -0.666730 -0.220307  0.107169  ...  0.004135  0.077430 -0.023671  0.055320   

         94        95        96        97        98        99  
0 -0.044791  0.036437 -0.009703 -0.026487  0.041831 -0.035295  
1 -0.000165  0.002904 -0.007159  0.001037 -0.002595 -0.006432  
2 -0.029931  0.009599  0.032737  0.025055  0.110885  0.186447  
3  0.006735 -0.027729  0.134229 -0.033999 -0.069467  0.007398  
4  0.018005  0.091160  0.046763 -0.025365  0.005096 -0.007968  

[5 rows x 100 columns]

In [9]:
Xtrain.shape

(590540, 100)

In [10]:
from sklearn.ensemble import AdaBoostClassifier

In [11]:
clf = AdaBoostClassifier(n_estimators=500, learning_rate=0.01)

In [12]:
clf.fit(Xtrain, Ytrain)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.01,
                   n_estimators=500, random_state=None)

In [13]:
from sklearn.metrics import log_loss, classification_report, confusion_matrix

In [14]:
Ytrain_ = clf.predict(Xtrain)

In [15]:
print(log_loss(Ytrain, Ytrain_))
print(confusion_matrix(Ytrain, Ytrain_))
print(classification_report(Ytrain, Ytrain_))

1.2085121018864764
[[569877      0]
 [ 20663      0]]


C:\Anaconda3\envs\dsmldl\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.97      1.00      0.98    569877
           1       0.00      0.00      0.00     20663

    accuracy                           0.97    590540
   macro avg       0.48      0.50      0.49    590540
weighted avg       0.93      0.97      0.95    590540



In [16]:
Xtest = pickle.load(open('Xtest_ANN.data', 'rb'))

In [17]:
Xtest = pca.transform(Xtest)

In [18]:
Ytest_ = clf.predict_proba(Xtest)

In [19]:
submission = pd.read_csv('./raw/sample_submission.csv', index_col='TransactionID')

In [20]:
submission.count()

isFraud    506691
dtype: int64

In [21]:
submission['isFraud'] = Ytest_
submission.head()

isFraud
TransactionID          
3663549        0.673445
3663550        0.682450
3663551        0.675011
3663552        0.698757
3663553        0.682812

In [22]:
submission['isFraud'] = 1 - submission['isFraud']

In [23]:
submission[submission['isFraud'] > 0.5].count()

isFraud    0
dtype: int64

In [24]:
submission.to_csv('predicted_PCA_ABC.csv')

In [25]:
pickle.dump(clf, open('clf_PCA_ABC.model', 'wb'), protocol=4)