In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
import pickle

In [3]:
df_train_id = pd.read_csv('./raw/train_identity.csv', index_col='TransactionID')
df_train_id.head()

id_01     id_02  id_03  id_04  id_05  id_06  id_07  id_08  \
TransactionID                                                              
2987004          0.0   70787.0    NaN    NaN    NaN    NaN    NaN    NaN   
2987008         -5.0   98945.0    NaN    NaN    0.0   -5.0    NaN    NaN   
2987010         -5.0  191631.0    0.0    0.0    0.0    0.0    NaN    NaN   
2987011         -5.0  221832.0    NaN    NaN    0.0   -6.0    NaN    NaN   
2987016          0.0    7460.0    0.0    0.0    1.0    0.0    NaN    NaN   

               id_09  id_10  ...                id_31 id_32      id_33  \
TransactionID                ...                                         
2987004          NaN    NaN  ...  samsung browser 6.2  32.0  2220x1080   
2987008          NaN    NaN  ...   mobile safari 11.0  32.0   1334x750   
2987010          0.0    0.0  ...          chrome 62.0   NaN        NaN   
2987011          NaN    NaN  ...          chrome 62.0   NaN        NaN   
2987016          0.0    0.0  ...          chrome 62.0  24.0   1280x800   

                        id_34 id_35 id_36  id_37  id_38  DeviceType  \
TransactionID                                                         
2987004        match_status:2     T     F      T      T      mobile   
2987008        match_status:1     T     F      F      T      mobile   
2987010                   NaN     F     F      T      T     desktop   
2987011                   NaN     F     F      T      T     desktop   
2987016        match_status:2     T     F      T      T     desktop   

                                  DeviceInfo  
TransactionID                                 
2987004        SAMSUNG SM-G892A Build/NRD90M  
2987008                           iOS Device  
2987010                              Windows  
2987011                                  NaN  
2987016                                MacOS  

[5 rows x 40 columns]

In [4]:
df_train_tid = pd.read_csv('./raw/train_transaction.csv', index_col='TransactionID')
df_train_tid.head()

isFraud  TransactionDT  TransactionAmt ProductCD  card1  card2  \
TransactionID                                                                   
2987000              0          86400            68.5         W  13926    NaN   
2987001              0          86401            29.0         W   2755  404.0   
2987002              0          86469            59.0         W   4663  490.0   
2987003              0          86499            50.0         W  18132  567.0   
2987004              0          86506            50.0         H   4497  514.0   

               card3       card4  card5   card6  ...  V330  V331  V332  V333  \
TransactionID                                    ...                           
2987000        150.0    discover  142.0  credit  ...   NaN   NaN   NaN   NaN   
2987001        150.0  mastercard  102.0  credit  ...   NaN   NaN   NaN   NaN   
2987002        150.0        visa  166.0   debit  ...   NaN   NaN   NaN   NaN   
2987003        150.0  mastercard  117.0   debit  ...   NaN   NaN   NaN   NaN   
2987004        150.0  mastercard  102.0  credit  ...   0.0   0.0   0.0   0.0   

              V334 V335  V336  V337  V338  V339  
TransactionID                                    
2987000        NaN  NaN   NaN   NaN   NaN   NaN  
2987001        NaN  NaN   NaN   NaN   NaN   NaN  
2987002        NaN  NaN   NaN   NaN   NaN   NaN  
2987003        NaN  NaN   NaN   NaN   NaN   NaN  
2987004        0.0  0.0   0.0   0.0   0.0   0.0  

[5 rows x 393 columns]

In [5]:
df_test_id = pd.read_csv('./raw/test_identity.csv', index_col='TransactionID')
df_test_id.head()

id_01     id_02  id_03  id_04  id_05  id_06  id_07  id_08  \
TransactionID                                                              
3663586        -45.0  280290.0    NaN    NaN    0.0    0.0    NaN    NaN   
3663588          0.0    3579.0    0.0    0.0    0.0    0.0    NaN    NaN   
3663597         -5.0  185210.0    NaN    NaN    1.0    0.0    NaN    NaN   
3663601        -45.0  252944.0    0.0    0.0    0.0    0.0    NaN    NaN   
3663602        -95.0  328680.0    NaN    NaN    7.0  -33.0    NaN    NaN   

               id_09  id_10  ...                    id_31 id_32     id_33  \
TransactionID                ...                                            
3663586          NaN    NaN  ...  chrome 67.0 for android   NaN       NaN   
3663588          0.0    0.0  ...  chrome 67.0 for android  24.0  1280x720   
3663597          NaN    NaN  ...       ie 11.0 for tablet   NaN       NaN   
3663601          0.0    0.0  ...  chrome 67.0 for android   NaN       NaN   
3663602          NaN    NaN  ...  chrome 67.0 for android   NaN       NaN   

                        id_34 id_35 id_36  id_37  id_38  DeviceType  \
TransactionID                                                         
3663586                   NaN     F     F      T      F      mobile   
3663588        match_status:2     T     F      T      T      mobile   
3663597                   NaN     F     T      T      F     desktop   
3663601                   NaN     F     F      T      F      mobile   
3663602                   NaN     F     F      T      F      mobile   

                                DeviceInfo  
TransactionID                               
3663586        MYA-L13 Build/HUAWEIMYA-L13  
3663588               LGLS676 Build/MXB48T  
3663597                        Trident/7.0  
3663601        MYA-L13 Build/HUAWEIMYA-L13  
3663602               SM-G9650 Build/R16NW  

[5 rows x 40 columns]

In [6]:
df_test_tid = pd.read_csv('./raw/test_transaction.csv', index_col='TransactionID')
df_test_tid.head()

TransactionDT  TransactionAmt ProductCD  card1  card2  card3  \
TransactionID                                                                 
3663549             18403224           31.95         W  10409  111.0  150.0   
3663550             18403263           49.00         W   4272  111.0  150.0   
3663551             18403310          171.00         W   4476  574.0  150.0   
3663552             18403310          284.95         W  10989  360.0  150.0   
3663553             18403317           67.95         W  18018  452.0  150.0   

                    card4  card5  card6  addr1  ...  V330  V331  V332 V333  \
TransactionID                                   ...                          
3663549              visa  226.0  debit  170.0  ...   NaN   NaN   NaN  NaN   
3663550              visa  226.0  debit  299.0  ...   NaN   NaN   NaN  NaN   
3663551              visa  226.0  debit  472.0  ...   NaN   NaN   NaN  NaN   
3663552              visa  166.0  debit  205.0  ...   NaN   NaN   NaN  NaN   
3663553        mastercard  117.0  debit  264.0  ...   NaN   NaN   NaN  NaN   

              V334  V335  V336  V337  V338  V339  
TransactionID                                     
3663549        NaN   NaN   NaN   NaN   NaN   NaN  
3663550        NaN   NaN   NaN   NaN   NaN   NaN  
3663551        NaN   NaN   NaN   NaN   NaN   NaN  
3663552        NaN   NaN   NaN   NaN   NaN   NaN  
3663553        NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 392 columns]

In [7]:
print(df_train_id.shape)
print(df_train_tid.shape)
print(df_test_id.shape)
print(df_test_tid.shape)

(144233, 40)
(590540, 393)
(141907, 40)
(506691, 392)


In [9]:
idx1 = pd.Index(df_train_id.index)
idx2 = pd.Index(df_train_tid.index)
idx1.intersection(idx2)

Int64Index([2987004, 2987008, 2987010, 2987011, 2987016, 2987017, 2987022,
            2987038, 2987040, 2987048,
            ...
            3577495, 3577499, 3577501, 3577506, 3577509, 3577521, 3577526,
            3577529, 3577531, 3577534],
           dtype='int64', name='TransactionID', length=144233)

In [11]:
def check_null_values(df):
    for column in df.columns:
        print('Column Name:', column, '\nHas null values:',df[column].isna().any(), '\nAmount of null values:', df[column].isna().sum())
        print('Values - Count')
        print(df[column].value_counts())
        print()

In [12]:
def replace_null_values(df):
    for column in df.columns:
        if(df[column].isna().any()):
            print(column, df[column].isna().sum())
            def replace():
                global i
                values = df[column].value_counts().index
                counts = df[column].value_counts().values
                counts = counts/counts.sum()
                yield np.random.choice(values,replace=False, p=counts)
            new_value = replace()
            df[column].fillna(value=next(new_value), inplace=True)
    for column in df.columns:
        print(column, df[column].isna().sum())
        if(df[column].isna().any()):
            print('Column:', column, 'has null values')
        else:
            print('No Null values in column')

In [16]:
df_train = df_train_tid.join(df_train_id, on='TransactionID',how='left', sort=True)
df_test = df_test_tid.join(df_test_id, on='TransactionID', how='left', sort=True)

In [17]:
print(df_train.shape)
print(df_test.shape)

(590540, 433)
(506691, 432)


In [18]:
del(df_train_tid)
del(df_train_id)
del(df_test_tid)
del(df_test_id)

In [19]:
df_train['isFraud'].fillna(value=0.0, inplace=True)
df_test['isFraud'] = -1

In [20]:
print(df_train.shape)
print(df_test.shape)

(590540, 433)
(506691, 433)


In [21]:
df_X = pd.concat([df_train, df_test], axis=0)
print(df_X.shape)

C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


(1097231, 433)


In [22]:
del(df_train)
del(df_test)

In [23]:
df_X.shape

(1097231, 433)

In [24]:
df_X['id_30'].unique()

array([nan, 'Android 7.0', 'iOS 11.1.2', 'Mac OS X 10_11_6', 'Windows 10',
       'Android', 'Linux', 'iOS 11.0.3', 'Mac OS X 10_7_5',
       'Mac OS X 10_12_6', 'Mac OS X 10_13_1', 'iOS 11.1.0',
       'Mac OS X 10_9_5', 'Windows 7', 'Windows 8.1', 'Mac', 'iOS 10.3.3',
       'Mac OS X 10.12', 'Mac OS X 10_10_5', 'Mac OS X 10_11_5',
       'iOS 9.3.5', 'Android 5.1.1', 'Android 7.1.1', 'Android 6.0',
       'iOS 10.3.1', 'Mac OS X 10.9', 'iOS 11.1.1', 'Windows Vista',
       'iOS 10.3.2', 'iOS 11.0.2', 'Mac OS X 10.11', 'Android 8.0.0',
       'iOS 10.2.0', 'iOS 10.2.1', 'iOS 11.0.0', 'Mac OS X 10.10',
       'Mac OS X 10_12_3', 'Mac OS X 10_12', 'Android 6.0.1', 'iOS',
       'Mac OS X 10.13', 'Mac OS X 10_12_5', 'Mac OS X 10_8_5',
       'iOS 11.0.1', 'iOS 10.0.2', 'Android 5.0.2', 'Windows XP',
       'iOS 11.2.0', 'Mac OS X 10.6', 'Windows 8', 'Mac OS X 10_6_8',
       'Mac OS X 10_11_4', 'Mac OS X 10_12_1', 'iOS 10.1.1',
       'Mac OS X 10_11_3', 'Mac OS X 10_12_4', 'Mac OS X 10

In [25]:
df_X['id_30'].replace(to_replace=r'(^Windows).*$', value='Windows', regex=True, inplace=True)
df_X['id_30'].replace(to_replace=r'(^Android).*$', value='Android', regex=True, inplace=True)
df_X['id_30'].replace(to_replace=r'(^iOS).*$', value='iOS', regex=True, inplace=True)
df_X['id_30'].replace(to_replace=r'(^Mac).*$', value='Mac', regex=True, inplace=True)
df_X['id_30'].unique()

array([nan, 'Android', 'iOS', 'Mac', 'Windows', 'Linux', 'func', 'other'],
      dtype=object)

In [26]:
df_X['id_31'].unique()

array([nan, 'samsung browser 6.2', 'mobile safari 11.0', 'chrome 62.0',
       'chrome 62.0 for android', 'edge 15.0', 'mobile safari generic',
       'chrome 49.0', 'chrome 61.0', 'edge 16.0', 'safari generic',
       'edge 14.0', 'chrome 56.0 for android', 'firefox 57.0',
       'chrome 54.0 for android', 'mobile safari uiwebview', 'chrome',
       'chrome 62.0 for ios', 'firefox', 'chrome 60.0 for android',
       'mobile safari 10.0', 'chrome 61.0 for android',
       'ie 11.0 for desktop', 'ie 11.0 for tablet', 'mobile safari 9.0',
       'chrome generic', 'other', 'chrome 59.0 for android',
       'firefox 56.0', 'android webview 4.0', 'chrome 55.0', 'opera 49.0',
       'ie', 'chrome 55.0 for android', 'firefox 52.0',
       'chrome 57.0 for android', 'chrome 56.0',
       'chrome 46.0 for android', 'chrome 58.0', 'firefox 48.0',
       'chrome 59.0', 'samsung browser 4.0', 'edge 13.0',
       'chrome 53.0 for android', 'chrome 58.0 for android',
       'chrome 60.0', 'mobile sa

In [27]:
df_X['id_31'].replace(to_replace=r'^(chrome).*$', value='chrome', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^([s|S]amsung).*$', value='samsung', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(safari).*$', value='safari', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^.*\s(safari).*$', value='safari', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(edge).*$', value='edge', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(ie).*$', value='ie', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(firefox).*$', value='firefox', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(Mozilla).*$', value='firefox', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(android).*$', value='android', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(opera).*$', value='opera', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(Generic).*$', value='android', regex=True, inplace=True)
df_X['id_31'].replace(to_replace=r'^(google).*$', value='google', regex=True, inplace=True)
df_X['id_31'].unique()

array([nan, 'samsung', 'safari', 'chrome', 'edge', 'firefox', 'ie',
       'other', 'android', 'opera', 'mobile', 'aol', 'silk', 'waterfox',
       'Nokia/Lumia', 'puffin', 'Microsoft/Windows', 'cyberfox',
       'ZTE/Blade', 'palemoon', 'maxthon', 'line', 'LG/K-200', 'iron',
       'BLU/Dash', 'seamonkey', 'M4Tel/M4', 'comodo', 'Lanix/Ilium',
       'chromium', 'Inco/Minion', 'Cherry', 'icedragon', 'google',
       'facebook', 'rim', 'uc', 'blackberry'], dtype=object)

In [28]:
df_X['id_33'].unique()

array([nan, '2220x1080', '1334x750', '1280x800', '1366x768', '1920x1080',
       '1680x1050', '1136x640', '5120x2880', '2880x1800', '1920x1200',
       '2560x1600', '2048x1536', '1024x768', '1280x720', '2560x1440',
       '2208x1242', '2001x1125', '1440x900', '1600x900', '2672x1440',
       '1280x1024', '960x540', '2732x2048', '2436x1125', '2048x1152',
       '2960x1440', '1024x600', '855x480', '4096x2304', '2160x1440',
       '2562x1442', '801x480', '2736x1824', '3441x1440', '2880x1620',
       '3840x2160', '1638x922', '1280x768', '1360x768', '1280x960',
       '3440x1440', '1152x720', '1280x1025', '3360x2100', '2304x1296',
       '1152x864', '3200x1800', '2112x1188', '2224x1668', '2400x1350',
       '2000x1125', '1600x1000', '2560x1080', '1728x972', '3000x2000',
       '1024x640', '3840x2400', '2304x1440', '1280x600', '1400x1050',
       '1600x1200', '3201x1800', '1356x900', '1344x756', '1624x1080',
       '1536x864', '1800x1125', '1920x1281', '2961x1442', '1366x1024',
       '1344x8

In [29]:
def mod(x):
    if type(x) == type(''):
        x = x.split(sep='x')
        x = int(x[0])*int(x[1])
        return x
    else:
        return np.nan

In [30]:
df_X['id_33'] = df_X['id_33'].map(mod)
df_X['id_33'].value_counts()

2073600.0     33742
1049088.0     15046
1000500.0     11550
2742336.0      9113
1296000.0      8127
              ...  
4986816.0         1
1329505.0         1
4855501.0         1
33177600.0        1
9222241.0         1
Name: id_33, Length: 455, dtype: int64

In [31]:
df_X['id_33'].isna().sum()

953271

In [32]:
df_X['P_emaildomain'].replace(to_replace=r'(\.\w+)+$', value='', regex=True, inplace=True)

In [33]:
df_X['R_emaildomain'].replace(to_replace=r'(\.\w+)+$', value='', regex=True, inplace=True)

In [34]:
df_X['P_emaildomain'].unique()

array([nan, 'gmail', 'outlook', 'yahoo', 'mail', 'anonymous', 'hotmail',
       'verizon', 'aol', 'me', 'comcast', 'optonline', 'cox', 'charter',
       'rocketmail', 'prodigy', 'embarqmail', 'icloud', 'live', 'att',
       'juno', 'ymail', 'sbcglobal', 'bellsouth', 'msn', 'q',
       'centurylink', 'servicios-ta', 'earthlink', 'cfl', 'roadrunner',
       'netzero', 'gmx', 'suddenlink', 'frontiernet', 'windstream',
       'frontier', 'mac', 'aim', 'web', 'twc', 'cableone', 'sc', 'ptd',
       'protonmail', 'scranton'], dtype=object)

In [35]:
df_X['R_emaildomain'].unique()

array([nan, 'gmail', 'hotmail', 'outlook', 'anonymous', 'charter',
       'prodigy', 'comcast', 'live', 'icloud', 'yahoo', 'aol', 'juno',
       'att', 'verizon', 'bellsouth', 'servicios-ta', 'ymail', 'msn',
       'optonline', 'gmx', 'aim', 'mail', 'me', 'cox', 'earthlink',
       'embarqmail', 'web', 'sbcglobal', 'scranton', 'mac', 'twc',
       'roadrunner', 'frontiernet', 'q', 'windstream', 'suddenlink',
       'ptd', 'frontier', 'cfl', 'netzero', 'rocketmail', 'centurylink',
       'protonmail', 'cableone', 'sc'], dtype=object)

In [36]:
df_X['DeviceInfo'].value_counts()

Windows        92710
iOS Device     38502
MacOS          23722
Trident/7.0    12330
rv:11.0         2650
               ...  
Tab2A7-10F         1
LG-US998           1
TR10RS1            1
ROCKET             1
B1-850             1
Name: DeviceInfo, Length: 2799, dtype: int64

In [37]:
df_X.drop(columns=['DeviceInfo'], inplace=True)

In [38]:
check_null_values(df_X)

Column Name: C1 
Has null values: True 
Amount of null values: 3
Values - Count
1.0       586742
2.0       197520
3.0        96569
4.0        53794
5.0        32851
           ...  
3959.0         1
1701.0         1
1702.0         1
1705.0         1
1822.0         1
Name: C1, Length: 2187, dtype: int64

Column Name: C10 
Has null values: True 
Amount of null values: 3
Values - Count
0.0       824420
1.0       192574
2.0        32690
3.0        13286
4.0         6838
           ...  
1456.0         1
1452.0         1
3144.0         1
1449.0         1
3030.0         1
Name: C10, Length: 1387, dtype: int64

Column Name: C11 
Has null values: True 
Amount of null values: 3
Values - Count
1.0       731792
2.0       168780
3.0        61642
4.0        28478
5.0        16366
           ...  
1823.0         1
458.0          1
1825.0         1
1826.0         1
511.0          1
Name: C11, Length: 1834, dtype: int64

Column Name: C12 
Has null values: True 
Amount of null values: 3
Values - Count


In [39]:
replace_null_values(df_X)

C1 3
C10 3
C11 3
C12 3
C13 4748
C14 3
C2 3
C3 3
C4 3
C5 3
C6 3
C7 3
C8 3
C9 3
D1 7300
D10 88567
D11 455805
D12 963260
D13 911895
D14 919850
D15 101182
D2 515566
D3 466020
D4 245773
D5 534216
D6 899261
D7 998181
D8 947967
D9 947967
DeviceType 819490
M1 447739
M2 447739
M3 447739
M4 519189
M5 660114
M6 328299
M7 581283
M8 581256
M9 581256
P_emaildomain 163648
R_emaildomain 824070
V1 455805
V10 455805
V100 314
V101 314
V102 314
V103 314
V104 314
V105 314
V106 314
V107 314
V108 314
V109 314
V11 455805
V110 314
V111 314
V112 314
V113 314
V114 314
V115 314
V116 314
V117 314
V118 314
V119 314
V12 88662
V120 314
V121 314
V122 314
V123 314
V124 314
V125 314
V126 314
V127 314
V128 314
V129 314
V13 88662
V130 314
V131 314
V132 314
V133 314
V134 314
V135 314
V136 314
V137 314
V138 939501
V139 939501
V14 88662
V140 939501
V141 939501
V142 939501
V143 939225
V144 939225
V145 939225
V146 939501
V147 939501
V148 939501
V149 939501
V15 88662
V150 939225
V151 939225
V152 939225
V153 939501
V154 939501
V

In [40]:
df_X.shape

(1097231, 432)

In [41]:
dum_cols = []
for column in df_X.columns:
    if df_X[column].dtype == 'object':
        dum_cols.append(column)
dum_cols

['DeviceType',
 'M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M7',
 'M8',
 'M9',
 'P_emaildomain',
 'ProductCD',
 'R_emaildomain',
 'card4',
 'card6',
 'id_12',
 'id_15',
 'id_16',
 'id_23',
 'id_27',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38']

In [42]:
df_X = pd.get_dummies(df_X, columns=dum_cols)
print(df_X.shape)
del(dum_cols)

(1097231, 599)


In [43]:
df_train = df_X[df_X['isFraud'] != -1]
df_test = df_X[df_X['isFraud'] == -1]
del(df_X)

In [44]:
print(df_train.shape)
print(df_test.shape)

(590540, 599)
(506691, 599)


In [45]:
Ytrain = df_train['isFraud']
Xtrain = df_train.drop(columns=['isFraud'])
Xtest = df_test.drop(columns=['isFraud'])
print(Xtrain.shape)
print(Ytrain.shape)
print(Xtest.shape)
pickle.dump(Ytrain, open('Ytrain_ANN.data', 'wb'))

(590540, 598)
(590540,)
(506691, 598)


In [46]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [47]:
scaler.fit(Xtrain)
pickle.dump(scaler, open('scaler_ANN.scaler', 'wb'))
Xtraincols = Xtrain.columns
Xtrainindex = Xtrain.index
Xtestcols = Xtest.columns
Xtestindex = Xtest.index

In [48]:
Xtrain = pd.DataFrame(data=scaler.transform(Xtrain), index=Xtrainindex, columns=Xtraincols)

In [49]:
pickle.dump(Xtrain, open('Xtrain_ANN.data', 'wb'), protocol=4)

In [50]:
Xtest = pd.DataFrame(data=scaler.transform(Xtest), index=Xtestindex, columns=Xtestcols)

In [51]:
pickle.dump(Xtest, open('Xtest_ANN.data', 'wb'), protocol=4)

In [52]:
del(scaler)

In [53]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras import optimizers

Using TensorFlow backend.


In [54]:
clf = Sequential()

W0830 14:10:53.558756  6916 deprecation_wrapper.py:119] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [55]:
clf.add(Dense(units=400, activation='relu', kernel_initializer='uniform', input_dim=598, bias_initializer='zeros'))
clf.add(Dropout(rate=0.1))

W0830 14:10:53.599818  6916 deprecation_wrapper.py:119] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0830 14:10:53.607819  6916 deprecation_wrapper.py:119] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0830 14:10:53.638823  6916 deprecation_wrapper.py:119] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\backend\tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0830 14:10:53.658821  6916 deprecation.py:506] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for up

In [56]:
clf.add(Dense(units=400, activation='relu', kernel_initializer='uniform', bias_initializer='zeros'))
clf.add(Dropout(rate=0.1))

In [57]:
clf.add(Dense(units=400, activation='relu', kernel_initializer='uniform', bias_initializer='zeros'))
clf.add(Dropout(rate=0.1))

In [58]:
clf.add(Dense(units=1, activation='sigmoid', kernel_initializer='uniform'))

In [59]:
opt_adam = optimizers.Adam(lr=0.001, epsilon=1e-8)

In [60]:
clf.compile(optimizer=opt_adam, loss='binary_crossentropy', metrics=['accuracy'])

W0830 14:10:53.979834  6916 deprecation_wrapper.py:119] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0830 14:10:53.999837  6916 deprecation_wrapper.py:119] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0830 14:10:54.012838  6916 deprecation.py:323] From C:\Anaconda3\envs\ds-ml-dl\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [61]:
clf.fit(Xtrain, Ytrain, epochs=50, validation_split=0.1, shuffle=True)

Train on 531486 samples, validate on 59054 samples
Epoch 1/50
531486/531486 [==============================] - 108s 204us/step - loss: 0.1145 - acc: 0.9700 - val_loss: 0.1143 - val_acc: 0.9680
Epoch 2/50
531486/531486 [==============================] - 110s 207us/step - loss: 0.1068 - acc: 0.9718 - val_loss: 0.1144 - val_acc: 0.9694
Epoch 3/50
531486/531486 [==============================] - 111s 210us/step - loss: 0.1036 - acc: 0.9726 - val_loss: 0.1129 - val_acc: 0.9689
Epoch 4/50
531486/531486 [==============================] - 111s 209us/step - loss: 0.1015 - acc: 0.9730 - val_loss: 0.1217 - val_acc: 0.9664
Epoch 5/50
531486/531486 [==============================] - 111s 210us/step - loss: 0.0999 - acc: 0.9735 - val_loss: 0.1141 - val_acc: 0.9695
Epoch 6/50
531486/531486 [==============================] - 112s 210us/step - loss: 0.0989 - acc: 0.9738 - val_loss: 0.1133 - val_acc: 0.9691
Epoch 7/50
531486/531486 [==============================] - 113s 212us/step - loss: 0.0979 - acc:

In [62]:
clf.evaluate(Xtrain,Ytrain)

590540/590540 [==============================] - 31s 52us/step


[0.09716144740161634, 0.9737426761946693]

In [63]:
pickle.dump(clf, open('clf_ANN.model', 'wb'))
clf.save('clf_ANN.h5')
clf.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 400)               239600    
_________________________________________________________________
dropout_1 (Dropout)          (None, 400)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 400)               160400    
_________________________________________________________________
dropout_2 (Dropout)          (None, 400)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 400)               160400    
_________________________________________________________________
dropout_3 (Dropout)          (None, 400)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 401       
Total para

In [64]:
from sklearn.metrics import log_loss, classification_report, confusion_matrix

In [65]:
Ytrain_ = clf.predict(Xtrain) > 0.5

In [66]:
print(log_loss(Ytrain, Ytrain_))
print(confusion_matrix(Ytrain, Ytrain_))
print(classification_report(Ytrain, Ytrain_))

0.9068961470635257
[[569647    230]
 [ 15276   5387]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99    569877
           1       0.96      0.26      0.41     20663

    accuracy                           0.97    590540
   macro avg       0.97      0.63      0.70    590540
weighted avg       0.97      0.97      0.97    590540



In [67]:
del(Xtrain)
del(Ytrain)

In [68]:
Ytest_ = clf.predict(Xtest)
del(Xtest)

In [69]:
Ytest_

array([[0.01531565],
       [0.0129334 ],
       [0.03143975],
       ...,
       [0.02116528],
       [0.01636494],
       [0.02839588]], dtype=float32)

In [70]:
submission = pd.read_csv('./raw/sample_submission.csv', index_col='TransactionID')

In [71]:
submission.count()

isFraud    506691
dtype: int64

In [72]:
submission['isFraud'] = Ytest_
submission.head()

isFraud
TransactionID          
3663549        0.015316
3663550        0.012933
3663551        0.031440
3663552        0.008053
3663553        0.012449

In [73]:
submission.to_csv('predicted_ANN.csv')