In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
Xtrain = pickle.load(open('Xtrain_ANN.data', 'rb'))
Ytrain = pickle.load(open('Ytrain_ANN.data', 'rb'))

In [3]:
from sklearn.decomposition import PCA

In [4]:
pca = PCA(n_components=100)

In [5]:
pca.fit(Xtrain)

PCA(copy=True, iterated_power='auto', n_components=100, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [6]:
pca.explained_variance_

array([1.53691052, 0.51650046, 0.49245962, 0.44320213, 0.3996141 ,
       0.3728763 , 0.34904255, 0.30409751, 0.28935477, 0.22907146,
       0.20430351, 0.16881411, 0.1497853 , 0.13200864, 0.12425354,
       0.10653815, 0.10525059, 0.09735936, 0.09501407, 0.08820326,
       0.08559168, 0.08331366, 0.07050821, 0.06771544, 0.06389252,
       0.0575539 , 0.0527528 , 0.04716308, 0.04583233, 0.0448552 ,
       0.04237726, 0.04029173, 0.03876344, 0.03744882, 0.03641377,
       0.03532321, 0.03020686, 0.02742895, 0.02592265, 0.0257678 ,
       0.02362075, 0.02228836, 0.02159805, 0.02010956, 0.01944478,
       0.0177831 , 0.01717802, 0.01652731, 0.01607151, 0.01524205,
       0.01433245, 0.01363158, 0.01287726, 0.01244912, 0.01234272,
       0.01218818, 0.01184055, 0.01143178, 0.01127677, 0.01069909,
       0.01055574, 0.00980349, 0.00898264, 0.00890886, 0.00839821,
       0.00790664, 0.00773447, 0.00750845, 0.00715646, 0.00698996,
       0.00681666, 0.00666479, 0.00647881, 0.00585648, 0.00558

In [7]:
pca.singular_values_

array([952.68336905, 552.28042499, 539.27415161, 511.59373042,
       485.78566609, 469.25259601, 454.00797364, 423.77050403,
       413.37062837, 367.79835612, 347.34592657, 315.7393151 ,
       297.41227537, 279.20646124, 270.88107937, 250.8284875 ,
       249.30819895, 239.78010334, 236.87447345, 228.22678272,
       224.82265666, 221.81064765, 204.05353693, 199.97152569,
       194.24475783, 184.35786944, 176.50094352, 166.88810337,
       164.5168106 , 162.75364122, 158.19425543, 154.25250857,
       151.29878162, 148.71109277, 146.64158296, 144.42899561,
       133.56020352, 127.27083414, 123.7268522 , 123.35675119,
       118.10577656, 114.72639376, 112.93579207, 108.9746844 ,
       107.15829956, 102.47739454, 100.71885671,  98.79281371,
        97.42100045,  94.87371618,  91.99929024,  89.7216692 ,
        87.20390919,  85.74199322,  85.37479366,  84.83865111,
        83.62001001,  82.16394713,  81.60498987,  79.48728439,
        78.95298489,  76.08773854,  72.83266434,  72.53

In [8]:
Xtrain = pd.DataFrame(data=pca.transform(Xtrain))
Xtrain.head()

0         1         2         3         4         5         6   \
0  0.147497 -0.128136 -0.555639  0.292194 -0.168896  1.501089  0.938601   
1  0.215837 -0.316249 -0.480825  1.065285 -0.388672  0.314880  0.001645   
2 -1.357071  0.254334  0.212074 -0.170978  0.917643 -0.101091  0.896096   
3 -0.699646  0.090907 -0.430041  0.786889 -0.922474 -0.422978 -0.176333   
4  2.361831  0.017103  1.310205  1.881893 -0.120688 -0.377364  0.510768   

         7         8         9   ...        90        91        92        93  \
0  0.363685 -0.396042 -0.006756  ... -0.003403  0.013582  0.040575 -0.051422   
1 -0.663226 -1.176959  0.081671  ... -0.002372 -0.011060 -0.010868  0.010950   
2  0.363993  0.523769 -0.618342  ...  0.011291 -0.048961 -0.018383  0.007660   
3  0.432002  0.212042 -0.075838  ...  0.007092 -0.022068  0.057170 -0.013088   
4 -0.666730 -0.220307  0.107169  ...  0.005544  0.076101  0.015977  0.069559   

         94        95        96        97        98        99  
0 -0.040557  0.026501 -0.007043 -0.005600 -0.039398 -0.047619  
1  0.000706  0.003861 -0.000433 -0.007567  0.004233 -0.003780  
2 -0.026428 -0.006766  0.030467  0.016448 -0.194050  0.128164  
3  0.006710 -0.034595 -0.003494  0.132069  0.055701  0.039724  
4  0.018829  0.087929 -0.016971  0.044604  0.008291  0.012755  

[5 rows x 100 columns]

In [9]:
Xtrain.shape

(590540, 100)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
clf = RandomForestClassifier(n_estimators=1000, n_jobs=-1, criterion='entropy')

In [12]:
clf.fit(Xtrain, Ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [13]:
from sklearn.metrics import log_loss, classification_report, confusion_matrix

In [14]:
Ytrain_ = clf.predict(Xtrain)

In [15]:
print(log_loss(Ytrain, Ytrain_))
print(confusion_matrix(Ytrain, Ytrain_))
print(classification_report(Ytrain, Ytrain_))

9.99200722162641e-16
[[569877      0]
 [     0  20663]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    569877
           1       1.00      1.00      1.00     20663

    accuracy                           1.00    590540
   macro avg       1.00      1.00      1.00    590540
weighted avg       1.00      1.00      1.00    590540



In [16]:
Xtest = pickle.load(open('Xtest_ANN.data', 'rb'))

In [17]:
Xtest = pca.transform(Xtest)

In [18]:
Ytest_ = clf.predict_proba(Xtest)

In [19]:
submission = pd.read_csv('./raw/sample_submission.csv', index_col='TransactionID')

In [20]:
submission.count()

isFraud    506691
dtype: int64

In [21]:
submission['isFraud'] = Ytest_
submission.head()

isFraud
TransactionID         
3663549          0.975
3663550          0.983
3663551          0.981
3663552          0.996
3663553          0.989

In [22]:
submission['isFraud'] = 1 - submission['isFraud']

In [23]:
submission[submission['isFraud'] > 0.5].count()

isFraud    3160
dtype: int64

In [24]:
submission.to_csv('predicted_PCA_RFCv1.csv')

In [25]:
pickle.dump(clf, open('clf_PCA_RFCv1.model', 'wb'))